version: '3.9'

services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=notelook
      - POSTGRES_DB=notelook_db
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U postgres'" ]
      interval: 10s
      timeout: 3s
      retries: 3
  notelook-service:
    container_name: notelook-service
    build: .
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
