spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/notelook_db
    username: notelook
    password: S3cret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

jwt:
  key: secret